# Generated by Django 5.0.1 on 2024-01-09 11:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authapp", "0002_alter_customuser_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
            ],
        ),
    ]
