# Generated by Django 5.0.1 on 2024-01-09 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authapp", "0003_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
