# Generated by Django 5.0.1 on 2024-01-10 06:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidate", "0002_candidateprofile_about_candidateprofile_github_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidateprofile",
            name="portfolio",
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
