# Generated by Django 5.0.1 on 2024-01-10 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidate", "0003_candidateprofile_portfolio"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidateprofile",
            name="first_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="last_name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
