# Generated by Django 5.0.1 on 2024-01-11 13:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("candidate", "0006_candidateprofile_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="candidateprofile",
            name="award",
        ),
        migrations.RemoveField(
            model_name="candidateprofile",
            name="education",
        ),
        migrations.RemoveField(
            model_name="candidateprofile",
            name="experience",
        ),
    ]
