# Generated by Django 5.0.1 on 2024-01-13 07:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidate", "0008_alter_education_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidateprofile",
            name="extra_activities",
            field=models.TextField(blank=True, null=True),
        ),
    ]
