# Generated by Django 5.0.1 on 2024-01-10 04:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobpost",
            name="hunter",
        ),
        migrations.RenameField(
            model_name="companyprofile",
            old_name="name",
            new_name="company_name",
        ),
        migrations.RenameField(
            model_name="companyprofile",
            old_name="type",
            new_name="company_type",
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="designation",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="user_avatar",
            field=models.ImageField(blank=True, null=True, upload_to="hunter_avatar/"),
        ),
        migrations.DeleteModel(
            name="HunterProfile",
        ),
    ]
