# Generated by Django 5.0.1 on 2024-01-13 11:06

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidate", "0010_project"),
        ("company", "0002_remove_jobpost_hunter_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "expected_salary",
                    models.CharField(blank=True, max_length=5, null=True),
                ),
                ("cover_letter", models.TextField(blank=True)),
                (
                    "date",
                    models.DateField(
                        verbose_name=datetime.datetime(2024, 1, 13, 17, 6, 37, 774195)
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_applications",
                        to="company.jobpost",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_application_user",
                        to="candidate.candidateprofile",
                    ),
                ),
            ],
        ),
    ]
