# Generated by Django 5.0.1 on 2024-01-15 15:38

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0003_jobapplication"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="companyprofile",
            name="designation",
        ),
        migrations.RemoveField(
            model_name="companyprofile",
            name="user_avatar",
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="jobHunter_profile/"
            ),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="position",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="companyprofile",
            name="address",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="companyprofile",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="date",
            field=models.DateField(
                verbose_name=datetime.datetime(2024, 1, 15, 21, 38, 25, 474135)
            ),
        ),
    ]
