# Generated by Django 5.0.1 on 2024-01-15 15:39

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0004_remove_companyprofile_designation_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="date",
            field=models.DateField(
                verbose_name=datetime.datetime(2024, 1, 15, 21, 39, 8, 50125)
            ),
        ),
    ]
